version: '3.9'
services:
  # api:
  #   container_name: api
  #   image: ./
  #   ports:
  #     - 8090:8090
  
  postgres:
    container_name: postgres
    image: postgres:15.2-alpine 
    ports:
      - 5400:5432
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: postgres
    volumes:
      - postgres-db:/data/postgres

volumes:
  postgres-db:
    driver: local